### ISSUE TITLE
No module named apply_bpe

### ISSUE THREAD

**Issue by RamoramaInteractive** [rsennrich/subword-nmt#107]
After training the model I wanted to do the translation in the section translation https://awslabs.github.io/sockeye/tutorials/wmt.html, but I only receive
`/opt/conda/envs/rapids/bin/python3: No module named apply_bpe`,

How to fix this problem?

**Comment by rsennrich** [comment]
you'll have to follow one of the earlier steps in the tutorial to make this work (and this isn't persistent, so you'll have to repeat this for each session or add it to your .bashrc file:

`export PYTHONPATH=$(pwd)/subword-nmt:$PYTHONPATH`

(if you add it to your .bashrc file, make sure to provide the absolute path, not the one relative to your working directory (`$(pwd)`))

**Comment by RamoramaInteractive** [comment]
Hi Rico,

After re-adding export ` PYTHONPATH=$(pwd)/subword-nmt:$PYTHONPATH I was able to execute the translation, but it didn't return the expected output `he is a great guy and a family father .`, but nothing.

**Comment by rsennrich** [comment]
you can check if this error is related to subword-nmt by only executing the top three lines of the script (without the trailing `| \`). If this works properly, it's probably a problem with Sockeye. Remove the `2>/dev/null` part so you get error messages.

**Comment by RamoramaInteractive** [comment]
I found a solution for my problem! :)

My model hasn't even trained yet, so I probably couldn't do any translation due to the missing data like "metrics" and the "params".

What I find funny, I had to rewrite the Sockeye code like in the last WMT 2014 English-German Tutorial: https://awslabs.github.io/sockeye/tutorials/wmt_large.html

Here is another link with important hints: https://github.com/awslabs/sockeye/issues/981

Thank you Rico! 👍 I will close this issue now.

**Comment by RamoramaInteractive** [comment]
After executing the translate code, I got a different error.

```
/data/subword-nmt/apply_bpe.py:396: DeprecationWarning: this script's location has moved to /data/subword-nmt/subword_nmt. This symbolic link will be removed in a future version. Please point to the new location, or install the package and use the command 'subword-nmt'
  DeprecationWarning
/data/subword-nmt/apply_bpe.py:416: ResourceWarning: unclosed file <_io.TextIOWrapper name='bpe.codes' mode='r' encoding='UTF-8'>
  args.codes = codecs.open(args.codes.name, encoding='utf-8')
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/data/subword-nmt/apply_bpe.py:422: ResourceWarning: unclosed file <_io.TextIOWrapper name='bpe.vocab.en' mode='r' encoding='UTF-8'>
  args.vocabulary = codecs.open(args.vocabulary.name, encoding='utf-8')
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/rapids/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/subword-nmt/apply_bpe.py", line 446, in <module>
    args.output.write(bpe.process_line(line, args.dropout))
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```
Why is the _broken pipe error_ happen?
