### ISSUE TITLE
Readme update please

### ISSUE THREAD

**Issue by youyinnn** [rsennrich/subword-nmt#109]
Don't know how to use the `subword-nmt learn-joint-bpe-and-vocab` and what it can do.

`subword-nmt learn-joint-bpe-and-vocab -h` is not enough.

Example please.

**Comment by rsennrich** [comment]
Hello Youyinnn,

an example, and explanation of what `learn-joint-bpe-and-vocab` does, is provided [here](https://github.com/rsennrich/subword-nmt#best-practice-advice-for-byte-pair-encoding-in-nmt).
