### ISSUE TITLE
How to avoid special char like '\t' being split by bpe

### ISSUE THREAD

**Issue by rangehow** [rsennrich/subword-nmt#112]
Hi, I have some problem in how to avoid '\t' being split into '@@ \t@@ '

I have tried `glossaries` after reading readme.me like this
`python subword-nmt/apply_bpe.py --glossaries \t,\n -c \
  wmt17_en_de/code <wmt17_en_de/tmp/constraint.en-de >wmt17_en_de/bpe.nocommer`

but it seems doesn't work, hope get some help from you : )

**Comment by rsennrich** [comment]
don't join multiple glossary entries by comma, but add space-separated and each enclosed in quotation marks. Finally, it seems that you need to escape backslashes:

`--glossaries "\\\t" "\\\n"` works for me in bash.

**Comment by rangehow** [comment]
Really appreciate it!! That works for me too. Maybe this specific usage about --glossaries can be add into readme.md and help in order to help more. Thanks for your in-time reply again!

**Comment by rsennrich** [comment]
I've now added an example to the Readme that shows how multiple glossary entries can be passed to subword-nmt.
