### ISSUE TITLE
Desired Final Vocabulary size

### ISSUE THREAD

**Issue by philip30** [rsennrich/subword-nmt#12]
Hi Rico,

Let say that I want to have the final vocabulary size of the input corpus is V_e. Would it be possible using the current implementation?

For example, Google wordpieces is trained to select "D" subwords that maximize the language-model likelihood of the training data.

Thank you!

**Comment by rsennrich** [comment]
Hello Philip,

yes, that's easily possible.

the final vocabulary size is the size of the initial character vocabulary, plus the number of merge operations ("-s") (there can be subword units that do not occur in the training corpus, especially with joint BPE; see footnotes 3 and 10 in the paper).

you can decrease your "-s" by the number of characters yourself, or check out this commit, which does it automatically: https://github.com/odashi/subword-nmt/commit/127a717024977b72b849cfcd26438dcfb7e71898

**Comment by philip30** [comment]
Thanks!
