### ISSUE TITLE
Different BPE models produced based on python version and/or stdin/argparse

### ISSUE THREAD

**Issue by ozancaglayan** [rsennrich/subword-nmt#13]
I'm using the latest github clone from this repository and I've noticed the following (Note that I removed the shebang line from `learn_bpe.py` so that it does not default to `/usr/bin/python`):
```
python2 learn_bpe.py -i input.en -s 1000 -o py2.argparse
sort py2.argparse > py2.argparse.sorted

cat input.en | python2 learn_bpe.py -s 1000 > py2.stdin
sort py2.stdin > py2.stdin.sorted

python3 learn_bpe.py -i input.en -s 1000 -o py3.argparse
sort py3.argparse > py3.argparse.sorted

cat input.en | python3 learn_bpe.py -s 1000 > py3.stdin
sort py3.stdin > py3.stdin.sorted

sha1sum *sorted
a8d78085206049c4ba8398e174e3467055b4b1f5  py2.argparse.sorted
a8d78085206049c4ba8398e174e3467055b4b1f5  py2.stdin.sorted
2e56fefcb09f9f6d829774fb230dd08d139ae711  py3.argparse.sorted
72c59258c73930284032e41fd1f6ffd848822f76  py3.stdin.sorted
```

I also attached the `input.en` file (as input.en.txt)
[input.en.txt](https://github.com/rsennrich/subword-nmt/files/792921/input.en.txt)

**Comment by ozancaglayan** [comment]
Well running python3 version produces a different model each time so it seems there is a non-deterministic stuff going on for Python 3.

**Comment by rsennrich** [comment]
we're using unordered data structures (dict and defaultdict), and taking the max value in these is non-deterministic. It may be possible to make it deterministic by replacing those data structures with OrderedDict, but I don't know how this affects performance, and determinism isn't officially guaranteed AFAIK even for taking the max in sorted data structures.

**Comment by ozancaglayan** [comment]
Those are non-deterministic in python2 as well but running the code 10 times with python2 always produces the same BPE model. Besides, when we apply the BPE model to text files, we obtain very different sentences each time.

**Comment by ozancaglayan** [comment]
I think its because of the `PYTHONHASHSEED` change introduced in Python 3.2. The code of learn_bpe.py is inherently complex in terms of data structure usage to fix so maybe you can add a notice in the README.md so that people is aware of this stochasticity.

**Comment by rsennrich** [comment]
I added the symbol pair as a secondary key to the max function - this should make the operation deterministic.

**Comment by ozancaglayan** [comment]
I confirm that this produce exactly same files on each python version. Thanks.
