### ISSUE TITLE
The given sed pattern may not be enough to remove @@

### ISSUE THREAD

**Issue by ozancaglayan** [rsennrich/subword-nmt#15]
Hi,

An MT system can generate hypotheses **ending** with a subword token which are not cleaned by the given sed pattern `s/\@\@ //g`:
```
echo 'foo@@ bar blah blah tot@@' | sed 's/@@ //g'
foobar blah blah tot@@

# Below seems to fix this by handling 0 or more spaces at the end
echo 'foo@@ bar blah blah tot@@' | sed 's/@@ *//g'
foobar blah blah tot
echo '
```

**Comment by josemonteiro** [comment]
I believe this is safer: `sed -E 's/(\@\@ )|(\@\@ ?$)//g'`: this only changes the behavior in the end of the string, matching one or zero whitespaces at the end.

**Comment by rsennrich** [comment]
thanks for these comments; I updated the README.
