### ISSUE TITLE
Motivation for the change in final `<\w>` addition in BPE

### ISSUE THREAD

**Issue by alvations** [rsennrich/subword-nmt#19]
@rsennrich What's the motivation for change in the `<\w>` addition in the "tuplization" of the word at https://github.com/rsennrich/subword-nmt/blob/master/learn_bpe.py#L188 ?

Previous, it was:

```
"stuff!" -> ('s', 't', 'u', 'f', 'f', '!', '</w>')
```

Now it's:

```
"stuff!" -> ('s', 't', 'u', 'f', 'f', '!</w>')
```

**Comment by rsennrich** [comment]
it eliminates a certain type of OOV at test time. Assuming you have the following at training time:

fund
und

the BPE operations learned are the following:

u n
un d
und </w>

"un" and "und" are ambiguous as to whether they are word-internal or word-final. So at test time, you may produce the OOV subword unit "und@@" (for instance when segmenting "funds"), or "un" (when segmenting "fun").

With </w> already added to the last character, you learn the following BPE operations:

u n
un d</w>

it's now non-ambiguous that "und" is a word-final subword unit, and "un@@" is word-internal, so apply_bpe.py will never produce "un" or "und@@".

**Comment by alvations** [comment]
@rsennrich Thanks for the explanation! Cool patch!
