### ISSUE TITLE
Adding some documentation to the statistics updates

### ISSUE THREAD

**Issue by alvations** [rsennrich/subword-nmt#21]
I'm not sure whether this is helpful but I wrote some comments on the `update_pair_statistics` function: https://github.com/alvations/subword-nmt/blob/patch-2/learn_bpe.py

@rsennrich if you find it's useful. I'll create a PR for merging otherwise, I'll leave it in my fork so that I don't get stunned for 10-15 mins every time I revisit the function ;P

**Comment by rsennrich** [comment]
Hi Liling,

thanks for the comments. Regarding your question on line 110: yes, this is to avoid an index error.

I've pushed some comments that are hopefully helpful, but a bit less verbose.
