### ISSUE TITLE
Serious bug in apply_bpe (mutable default parameter)

### ISSUE THREAD

**Issue by sklampfl** [rsennrich/subword-nmt#27]
I think there is a serious bug in `apply_bpe.py` resulting from having a mutable default parameter (`cache={}`) in the `encode` function (https://github.com/rsennrich/subword-nmt/blob/master/apply_bpe.py#L126).

I guess it's fine if you use the script as a command-line tool, but if I use multiple instances of the `BPE` class directly, I observe the following behavior:
```
In [1]: from apply_bpe import BPE

In [2]: bpe_de = BPE(open("/path/to/german.codes"))

In [3]: bpe_en = BPE(open("/path/to/english.codes"))

In [4]: bpe_de.segment("bewundere")
Out[4]: 'bewunder@@ e'

In [5]: bpe_en.segment("bewundere")
Out[5]: 'bewunder@@ e'
```
During the first `segment` call the `cache` dictionary is modified during `encode`, and the same instance of `cache` is then used in the second call of `encode`, essentially overwriting the codes loaded from file.

If I make the following simple modification
```
def encode(..., cache=None):
    if cache is None:
        cache = {}
    ...
```
I get the expected behavior:
```
In [1]: from apply_bpe import BPE

In [2]: bpe_de = BPE(open("/path/to/german.codes"))

In [3]: bpe_en = BPE(open("/path/to/english.codes"))

In [4]: bpe_de.segment("bewundere")
Out[4]: 'bewunder@@ e'

In [5]: bpe_en.segment("bewundere")
Out[5]: 'be@@ w@@ un@@ d@@ ere'
```

See also http://effbot.org/zone/default-values.htm

**Comment by rsennrich** [comment]
Hello Stefan,

thanks for pointing this out, this use case was indeed broken. Your solution disables the cache completely, but I've now changed the code so that the cache is persistent within a class instance, but not across class instances. See commit 88731360d8e7021bdae00c969f2a1ff0ce8f1970

**Comment by sklampfl** [comment]
Thanks for the immediate response. I think your solution works fine.
