### ISSUE TITLE
Is it suitable for any language?

### ISSUE THREAD

**Issue by atricfox** [rsennrich/subword-nmt#28]
Is it suitable for any language? I want use it in Chinese, is it correct ?

**Comment by rsennrich** [comment]
We successfully used BPE, along with Jieba for word segmentation, for Chinese. See https://arxiv.org/pdf/1708.00726.pdf for more details.

**Comment by atricfox** [comment]
@rsennrich I see. Thank you very much! I have used Jieba before.
