### ISSUE TITLE
Subword for Arabic

### ISSUE THREAD

**Issue by kmario23** [rsennrich/subword-nmt#30]
Hi @rsennrich! this is quite an interesting work! I'm interested in applying this subword units (BPE) approach for translation from Arabic to English. I see that this approach seems to work only for `romanized` text encodings. Are there any ways to apply it for _Arabic_ text?

 My idea is to generate these subword units for _Arabic and English_ and train **Ar-En NMT** system using [TensorFlow](https://github.com/tensorflow/nmt). I know the scripts work for English but I'm not sure about how to achieve the same subword unit generation for `Arabic`.

**Comment by rsennrich** [comment]
BPE works on Arabic, and recent publications have reported good results with it: https://arxiv.org/pdf/1709.00616.pdf

If there are any problems with encoding or similar, this is a bug and you can report it.
