### ISSUE TITLE
no pair has frequency >= 2. Stopping

### ISSUE THREAD

**Issue by yapingzhao** [rsennrich/subword-nmt#33]
python -m learn_joint_bpe_and_vocab --input corpus.en corpus.ch -s 30000 -o bpe.codes --write-vocabulary bpe.vocab.en bpe.vocab.ch
After running the above command, the following hints appear：no pair has frequency >= 2. Stopping。
I don't understand what this message means. I hope to give it a answer, thank you.

**Comment by rsennrich** [comment]
learn_bpe terminates under two conditions:
 - you have reached the defined number of merge operations.
 - there is no pair of subword units that occurs more than once.
if you try to learn BPE operations on a small corpus, you might encounter the second condition. Depending on your use case, this might be fine, but I would usually recommend to use a large corpus to learn BPE operations.

**Comment by yapingzhao** [comment]
Ok, I see.Thanks for your answer.
Thanks again!
