### ISSUE TITLE
support

### ISSUE THREAD

**Issue by bhagat02** [rsennrich/subword-nmt#43]
In the code generation we have to give declation+docstring as x.train and body as y.train. So, i am following your code and i did byte pair encoding as i am new to this field i really want to show you my work so that you can tell me whether i am going in a right direction or not.

As directed .. this is my vocab file for declaration and description which i got after using the shell command

<img width="641" alt="screen shot 2018-04-10 at 17 15 03" src="https://user-images.githubusercontent.com/30953931/38566019-03e4f306-3ce3-11e8-9dec-7a859ad035b3.png">

this is the vocab file of body 
<img width="420" alt="screen shot 2018-04-10 at 17 17 55" src="https://user-images.githubusercontent.com/30953931/38566085-26daf5f4-3ce3-11e8-925d-efcc5f09171c.png">

this is the declaration_description.bpe file
<img width="632" alt="screen shot 2018-04-10 at 17 18 56" src="https://user-images.githubusercontent.com/30953931/38566160-483469a6-3ce3-11e8-92ee-9365e547dca3.png">

this is the body.bpe file
<img width="627" alt="screen shot 2018-04-10 at 17 19 48" src="https://user-images.githubusercontent.com/30953931/38566194-67710d4c-3ce3-11e8-8909-3f935c5c69e6.png">

so , can u please guide me whether i am going in the right direction or not.
Thank you so much in advance 👍

**Comment by rsennrich** [comment]
at first glance, this looks fine.

**Comment by bhagat02** [comment]
Thank you so much for your time. :)
