### ISSUE TITLE
byte pair encoding

### ISSUE THREAD

**Issue by jigyasa06** [rsennrich/subword-nmt#44]
Hi, i want to know why do you use byte pair encoding for code generation task to further sub-tokenise it ? can't we proceed further directly to nematus without byte-pair encoding?

**Comment by rsennrich** [comment]
I assume you're referring to this paper: http://www.aclweb.org/anthology/I17-2053
if you don't perform subword segmentation, you will face OOV words in your model, both in the code documentation and the code itself.

**Comment by jigyasa06** [comment]
Dear Sennrich,

Yes, I am referring to this paper only but in the paper it is not mentioned
that why it is important to use it. I got to know by reading your research
paper on subword segmentation. Thank you so much for your help.

Best Regards,
Jigyasa Sakhuja
