### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by yapingzhao** [rsennrich/subword-nmt#45]
When I use the following command for BPE operation：
./apply_bpe.py -c bpe.train.mn < train.mn-zh.mn 
Terminal output error message：
Traceback (most recent call last):
  File "./apply_bpe.py", line 313, in <module>
    bpe = BPE(args.codes, args.merges, args.separator, vocabulary, args.glossaries)
  File "./apply_bpe.py", line 45, in __init__
    self.bpe_codes_reverse = dict([(pair[0] + pair[1], pair) for pair,i in self.bpe_codes.items()])
  File "./apply_bpe.py", line 45, in <listcomp>
    self.bpe_codes_reverse = dict([(pair[0] + pair[1], pair) for pair,i in self.bpe_codes.items()])
IndexError: tuple index out of range
I would like to ask what is the reason for this.
Looking forward to your advice or answers.
Best regards,

yapingzhao

**Comment by rsennrich** [comment]
This looks like your BPE file (bpe.train.mn) contains lines that are in the wrong format (i.e. not exactly two items per line). I added some error message to indicate where the problem occurs - can you try again with the newest version?

**Comment by yapingzhao** [comment]
Okay, thank you very much.

**Comment by rsennrich** [comment]
this should be fixed in commit 662efd1b9d34ae6d3bfdfd5e6dffe2c72f2e7285.

**Comment by learnbott** [comment]
oh man, thank you @rsennrich for this fix. Mine works w/o any hacks.
