### ISSUE TITLE
learn_bpe.py generates an invalid bpe file

### ISSUE THREAD

**Issue by lovasoa** [rsennrich/subword-nmt#46]
When training with `learn_bpe.py` and then trying to use the generated file, I get the following error: 

```
Error: invalid line in BPE codes file: e
The line should exist of exactly two subword units, separated by whitespace
```

This error message is not very useful as it does not indicate on what line the error is.

**Comment by lovasoa** [comment]
Here is the generated bpe file: https://gist.github.com/lovasoa/bc2883e20de5acb18a2368cb6ad016de

**Comment by rsennrich** [comment]
thanks for the report; this should be fixed in commit 662efd.

**Comment by loretoparisi** [comment]
@rsennrich it seems I'm having the same issue here https://github.com/rsennrich/subword-nmt/issues/76#issuecomment-479503681

**Comment by rsennrich** [comment]
This is a different issue, and commented on in #76.
