### ISSUE TITLE
apply_bpe.py doubles empty lines

### ISSUE THREAD

**Issue by emjotde** [rsennrich/subword-nmt#48]
Hi, 
it seems `apply_bpe.py` duplicates empty lines, minimal example:

```
echo -e '\n\n' | wc -l
3
```

and twice as many with the script.

```
echo -e '\n\n' | ./subword-nmt/apply_bpe.py -c bpe.codes | wc -l
6
```

Can you reproduce this?

**Comment by rsennrich** [comment]
thanks; fixed.
