### ISSUE TITLE
Pip version bug - ModuleNotFoundError: No module named 'learn_bpe'

### ISSUE THREAD

**Issue by sai-prasanna** [rsennrich/subword-nmt#51]
Installed with pip and python3 venv, calling the subword-nmt modules throws this error.

`subword-nmt learn-bpe -s 3000 < input.txt`

```
Traceback (most recent call last):
File "/<>/venv/bin/subword-nmt", line 7, in <module>
    from subword_nmt.subword_nmt import main
File "/<>/venv/lib/python3.6/site-packages/subword_nmt/subword_nmt.py", line 9, in <module>
    from learn_bpe import learn_bpe
ModuleNotFoundError: No module named 'learn_bpe'
```

I think we have to change the import to .learn_bpe

**Comment by rsennrich** [comment]
thank you for the report. This seems to affect pip installs with Python3, while Python2 works. I've patched this in 8012fd6607587112cd5772407b3162e7f6388451, but I compromised a bit, and subword_nmt.py can no longer be run as a script.
