### ISSUE TITLE
apply_bpe gives fewer segments than before

### ISSUE THREAD

**Issue by hsajjad** [rsennrich/subword-nmt#55]
Hi, I have been using `apply_bpe` from October 2016. I tested a recent copy of `apply_bpe` and the number of segments are significantly lower than before. I am using exactly the same settings and codes as before. Has something changed significantly in the algorithm for applying the codes that may be causing this issue?

**Comment by rsennrich** [comment]
Hello Hassan,

the only significant change in the behavior of apply_bpe is the 
treatment of UTF-8 whitespace and newlines. Before, they were treated as 
word boundaries, and silently converted into plain whitespace and 
newlines, which caused some bugs (especially the newlines part). The new 
behavior is to only treat plain whitespace as a word boundary, and 
special UTF-8 whitespace characters get treated as part of a word.

If you learn a new vocabulary with learn_bpe.py , there is also a new 
handling of the special end-of-line token to prevent the production of 
some spurious segmentations at test time: 
https://github.com/rsennrich/subword-nmt/issues/19

please let me know if this explains the difference you observe. If not, 
it would be great if you could share a minimal reproducible example of 
the different behavior.

best wishes,
Rico
