### ISSUE TITLE
Skip special tokens

### ISSUE THREAD

**Issue by voidmagic** [rsennrich/subword-nmt#65]
Hi there, I want to add some special tokens into my corpus, such as <UNK>, and keep it fixed. But apply bpe will tokenize it as `<@@ UN@@ K@@ >`. 
Is there a way to skip some special tokens?
Thanks.

**Comment by rsennrich** [comment]
`apply_bpe.py` has the `--glossaries` argument - any strings (or regular expressions) in the glossary will be ignored by BPE.

**Comment by voidmagic** [comment]
> `apply_bpe.py` has the `--glossaries` argument - any strings (or regular expressions) in the glossary will be ignored by BPE.

I see. Thanks!
