### ISSUE TITLE
UnicodeEncodeError when using subword-nmt learn-bpe with verbose mode

### ISSUE THREAD

**Issue by leoxiao2012** [rsennrich/subword-nmt#66]
My train text data is in Chinese. and it reports UnicodeEncodeError when using `subword-nmt learn-bpe`command with verbose mode on, while it works fine with learn_bpe.py script.
Then I check the code and find out the reason.
```py
    # python 2/3 compatibility
    if sys.version_info < (3, 0):
        sys.stderr = codecs.getwriter('UTF-8')(sys.stderr)
        sys.stdout = codecs.getwriter('UTF-8')(sys.stdout)
        sys.stdin = codecs.getreader('UTF-8')(sys.stdin)
    else:
        sys.stdin = io.TextIOWrapper(sys.stdin.buffer, encoding='utf-8')
        sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
```
It seems that command line `subwor-nmt learn-bpe` doesn't run the above codes, then `sys.stderr` used by verbose mode (see below)  would be the default system stderr，which encodes unicode with "ascii" encoding. 
```
        if verbose:
            sys.stderr.write('pair {0}: {1} {2} -> {1}{2} (frequency {3})\n'.format(i, most_frequent[0], most_frequent[1], stats[most_frequent]))
```

**Comment by rsennrich** [comment]
Thank you for reporting this. Yes, subword_bpe.py is never executed as a script, and I corrected this now in commit 955abfe7e5b653f3499ed3d2bcd4738d271ae2f6. Please let me know if there are any other issues.
