### ISSUE TITLE
bash: ./subword-nmt/subword-nmt/apply_bpe.py: No such file or directory

### ISSUE THREAD

**Issue by sanjita-suresh** [rsennrich/subword-nmt#74]
Hello, I am getting this error if I try to preprocess german data? I am curious if this works only for english?

**Comment by rsennrich** [comment]
try `subword-nmt/subword_nmt/apply_bpe.py`

**Comment by sanjita-suresh** [comment]
Yes I tried that but the error was still there

**Comment by rsennrich** [comment]
This command is relative to your current working directory, and assumes you've downloaded the scripts via git. If you don't want to worry about relative paths, install it via pip and just use the command `subword-nmt apply-bpe`

**Comment by sanjita-suresh** [comment]
Thank you. That works :)
