### ISSUE TITLE
About Programmatically usage

### ISSUE THREAD

**Issue by loretoparisi** [rsennrich/subword-nmt#76]
I'm trying to use the package programatically. I'm doing

```python
    from subword_nmt.apply_bpe import BPE, read_vocabulary
     # read/write files as UTF-8
    bpe_codes_fin = codecs.open(bpe_codes, encoding='utf-8')
    bpe_vocab_fin = codecs.open(bpe_vocab, encoding='utf-8')
    vocabulary = read_vocabulary(bpe_vocab_fin, vocabulary_threshold)

    bpe = BPE(bpe_codes_fin, merges=-1, separator='@@', vocab=vocabulary, glossaries=None)
    codes = bpe.process_line(line)
```

Is that correct? Also, I'm not sure of the `vocabulary_threshold`, since I do not see any default value. Is there any one?

Thank you.

**Comment by rsennrich** [comment]
This looks mostly fine. Two remarks:

- `vocabulary` is optional. Its function is described in the [README](https://github.com/rsennrich/subword-nmt#best-practice-advice-for-byte-pair-encoding-in-nmt). If you use it, you can provide a `vocabulary-threshold` (effectively filtering out low-frequency items from the vocabulary), but this is also optional.
- you will typically want to apply BPE to more than one line. If so, make sure that only the last line is executed repeatedly.

**Comment by loretoparisi** [comment]
Thank you, I'm going to split lines to handle both cases then. In my model I have both vocabulary and codes, but at this point my wonder becomes: how to get the right threshold? I mean assumed I have a vocabulary already, shall I have make some stats to get the lowest frequency words?

**Comment by loretoparisi** [comment]
@rsennrich I get this error: `Error: invalid line 1 in BPE codes file: e n 52708119`. 

My codes and vocabulary files are from FAIR LASER model:

- Codes: https://dl.fbaipublicfiles.com/laser/models/93langs.fcodes
- Vocab: https://dl.fbaipublicfiles.com/laser/models/93langs.fvocab

The vocabulary is loaded correctly through the `read_vocabulary` api, while I immediately get that error I presume when passing to the line

```python
    encoder = BPE(bpe_codes_fin, merges=-1, separator='@@', vocab=vocabulary, glossaries=None)
```

**Comment by rsennrich** [comment]
As to your first question, have a look at your vocabulary file - whether you set the threshold to 5 or 500 won't make a big difference for you, since most rare tokens are single (non-Latin) characters that won't be affected by this.

FAIR LASER uses a different BPE implementation ( https://github.com/glample/fastBPE ), which seems to store the BPE file in a different format. It might work if you simply remove the third item in each entry (the frequency), but I can't guarantee there's no other inconsistency, e.g. in how UTF-8 whitespace is handled.

**Comment by loretoparisi** [comment]
@rsennrich thank you, looking at the results it seems the problem is the third column only, but I will have a look at possibile UTF-8 issues as well, hopefully there are not. Specifically, in which cases it could fail? Thank you

**Comment by rsennrich** [comment]
try adding this as the first line to the BPE file:

```
#version: 0.2
```

the reason for this is explained in the [README](https://github.com/rsennrich/subword-nmt#how-implementation-differs-from-sennrich-et-al-2016). It looks like fastBPE implements the new variant (v 0.2) as well.

**Comment by loretoparisi** [comment]
@rsennrich  ok, so basically subword-nmt needs the comment to detect the version. The only issue I see is that if I have a pre-trained file it can happen that I cannot modify it. Thanks, closing.

**Comment by RenShuhuai-Andy** [comment]
> try adding this as the first line to the BPE file:
> 
> ```
> #version: 0.2
> ```
> 
> the reason for this is explained in the [README](https://github.com/rsennrich/subword-nmt#how-implementation-differs-from-sennrich-et-al-2016). It looks like fastBPE implements the new variant (v 0.2) as well.

Hi~ it doesn't work for me. The error log is `Error: invalid line 1 in BPE codes file: e n</w> 1423551864` before adding `#version: 0.2`, then it's `Error: invalid line 2 in BPE codes file: e n</w> 1423551864`...
The BPE file I used is downloaded from [fairseq: transformer.wmt19.en-de](https://github.com/pytorch/fairseq/tree/master/examples/translation), and I `export LANG=en_US.UTF-8; export LC_ALL=en_US.UTF-8`. Any advice?

**Comment by RenShuhuai-Andy** [comment]
> > try adding this as the first line to the BPE file:
> > ```
> > #version: 0.2
> > ```
> > 
> > 
> > the reason for this is explained in the [README](https://github.com/rsennrich/subword-nmt#how-implementation-differs-from-sennrich-et-al-2016). It looks like fastBPE implements the new variant (v 0.2) as well.
> 
> Hi~ it doesn't work for me. The error log is `Error: invalid line 1 in BPE codes file: e n</w> 1423551864` before adding `#version: 0.2`, then it's `Error: invalid line 2 in BPE codes file: e n</w> 1423551864` ...
> The BPE file I used is downloaded from [fairseq: transformer.wmt19.en-de](https://github.com/pytorch/fairseq/tree/master/examples/translation), and I `export LANG=en_US.UTF-8; export LC_ALL=en_US.UTF-8`. Any advice? @rsennrich

oh I have solved this problem, I set the bpe parameter incorrectly, sorry
