### ISSUE TITLE
How to recover the BPE

### ISSUE THREAD

**Issue by QAQ-v** [rsennrich/subword-nmt#80]

**Comment by tnq177** [comment]
simply replacing all "@@ " with "".  The readme has a command for that:
```
The original segmentation can be restored with a simple replacement:

sed -r 's/(@@ )|(@@ ?$)//g'
```

**Comment by QAQ-v** [comment]
Thanks... I got it when I submitted the issue =.=.. It's a really silly question..

**Comment by QAQ-v** [comment]
> simply replacing all "@@ " with "". The readme has a command for that:
> 
> ```
> The original segmentation can be restored with a simple replacement:
> 
> sed -r 's/(@@ )|(@@ ?$)//g'
> ```

Thanks! I got it when I submitted the issue =.=.. It's a really silly question..
