### ISSUE TITLE
Meaning of the output file of learn_bpe.py

### ISSUE THREAD

**Issue by Gromy1211** [rsennrich/subword-nmt#84]
Every line of the output file of learn.py is consisted of two subword units(for instance, `o f</w>`)

I am a little bit confused by these two units, does that mean `o` and ` f</w>` can be merged into `of<w>` when applying BPE?

Thanks for answering!

**Comment by rsennrich** [comment]
yes, this is correct. More specifically, the file lists all merge operations in the order in which they will be applied. To apply the merge operations to a new file, use `apply_bpe.py`.

**Comment by Gromy1211** [comment]
Thanks for the quick response!! I think I understand how the BPE algorithm works now ;)
