### ISSUE TITLE
Restoring BPE

### ISSUE THREAD

**Issue by Oxi84** [rsennrich/subword-nmt#93]
Hello,

What sed -r 's/(@@ )|(@@ ?$)//g' means?

Do you have a python code for this, from code, not from command line if that applies to command line?

Thanks

**Comment by rsennrich** [comment]
That's a simple regular expression that removes all '@@ ' in a line. Trailing '@@' is also removed. Equivalent Python code could look like this:

```
line = 'ab@@ def@@'
line = line.replace('@@ ', '')
if line.endswith('@@'):
  line = line[:-2]
```
