### ISSUE TITLE
BPE vocabulary config

### ISSUE THREAD

**Issue by anrizal** [rsennrich/subword-nmt#95]
Hello,

I am trying to replicate _Revisiting Low-Resource Neural Machine Translation: - A Case Study, paper_. I am not quite sure with the term BPE vocabulary in relation with subword-nmt

The paper mentioned BPE operations were 30000 which I assumed correlates with _bpe_operations_ parameters in subword_NMT.
How about **BPE vocabulary**, does this correlate with _--vocabulary-threshold_ parameters in subword_NMT ?

Thank you

**Comment by rsennrich** [comment]
You can find more documentation (and scripts) for this paper here: http://data.statmt.org/rsennrich/iwslt14_lowresource/

In short, we ran `learn_joint_bpe_and_vocab.py` with 30,000 merge operations, but used the _--vocabulary_threshold_ in `apply_bpe.py` to scale the vocabulary size to the respective amounts of training data.
